Repository NewSee-PJ/BE, pull requests merged in 2025-07, with the labels that each got.

#2 [Feature] #1 - Spring Security 기본 설정 및 비인증 경로 적용
  src/main/java/dgu/newsee/NewseeApplication.java
  src/main/java/dgu/newsee/global/RootController.java
  src/main/java/dgu/newsee/global/config/SecurityConfig.java
  src/main/java/dgu/newsee/global/config/SwaggerConfig.java
  src/main/java/dgu/newsee/global/config/WebConfig.java
Labels: ✨ feature

#10 ✨ [Feature] - JWT 기반 인증 처리 로직 구현
  src/main/java/dgu/newsee/domain/user/controller/UserController.java
  src/main/java/dgu/newsee/domain/user/converter/UserConverter.java
  src/main/java/dgu/newsee/domain/user/dto/UserDTO.java
  src/main/java/dgu/newsee/domain/user/dto/UserProfile.java
  src/main/java/dgu/newsee/domain/user/entity/Role.java
  src/main/java/dgu/newsee/domain/user/entity/User.java
  src/main/java/dgu/newsee/domain/user/repository/UserRepository.java
  src/main/java/dgu/newsee/domain/user/service/UserService.java
  src/main/java/dgu/newsee/domain/user/service/UserServiceImpl.java
  src/main/java/dgu/newsee/global/payload/ResponseCode.java
  src/main/java/dgu/newsee/global/payload/ResponseCodeType.java
  src/main/java/dgu/newsee/global/security/CustomUserDetails.java
  src/main/java/dgu/newsee/global/security/CustomUserDetailsService.java
  src/main/java/dgu/newsee/global/security/JwtAuthenticationFilter.java
  src/main/java/dgu/newsee/global/security/JwtAuthenticationProvider.java
  src/main/java/dgu/newsee/global/security/JwtAuthenticationToken.java
  src/main/java/dgu/newsee/global/security/JwtTokenProvider.java
  src/main/java/dgu/newsee/global/security/JwtUtil.java
  src/main/java/dgu/newsee/global/security/OAuthConstants.java
  src/main/java/dgu/newsee/global/security/OAuthProvider.java
  src/main/java/dgu/newsee/global/security/OAuthUtil.java
  src/main/resources/application.yml
Labels: ✨ feature, 🐸 하은 작업

#14 [Feature] #13 - 프로필 수정 API 구현
  src/main/java/dgu/newsee/domain/user/controller/UserController.java
  src/main/java/dgu/newsee/domain/user/converter/UserConverter.java
  src/main/java/dgu/newsee/domain/user/dto/UserDTO.java
  src/main/java/dgu/newsee/domain/user/entity/User.java
  src/main/java/dgu/newsee/domain/user/service/UserService.java
  src/main/java/dgu/newsee/domain/user/service/UserServiceImpl.java
  src/main/java/dgu/newsee/global/config/SecurityConfig.java
  src/main/java/dgu/newsee/global/exception/BaseErrorCode.java
  src/main/java/dgu/newsee/global/exception/GeneralException.java
  src/main/java/dgu/newsee/global/exception/UserException.java
  src/main/java/dgu/newsee/global/payload/ApiResponse.java
  src/main/java/dgu/newsee/global/payload/ResponseCode.java
  src/main/java/dgu/newsee/global/security/CustomUserDetails.java
Labels: ✨ feature, 🐸 하은 작업

#20 [Bug] #19 - workflow 파일에 JWT_SECRET_KEY 추가
  .github/workflows/main.yml
Labels: :bug: fix, 🐸 하은 작업

#24 [Fix] #23 - 사용자 이메일 중복 저장 방지를 위한 unique 제약 추가
  src/main/java/dgu/newsee/domain/user/entity/User.java
Labels: :bug: fix, 🐸 하은 작업

#26 [Feature] #8 - 프로필 조회 API
  src/main/java/dgu/newsee/domain/user/controller/UserController.java
  src/main/java/dgu/newsee/domain/user/converter/UserConverter.java
  src/main/java/dgu/newsee/domain/user/dto/UserDTO.java
  src/main/java/dgu/newsee/domain/user/service/UserService.java
  src/main/java/dgu/newsee/domain/user/service/UserServiceImpl.java
Labels: ✨ feature, 🐈‍⬛ 영신 작업

#22 [Feature] #21 - 뉴스 크롤링 API구현 (네이버뉴스기준)
  build.gradle
  src/main/java/dgu/newsee/domain/news/controller/NewsController.java
  src/main/java/dgu/newsee/domain/news/dto/NewsCrawlRequestDTO.java
  src/main/java/dgu/newsee/domain/news/dto/NewsCrawlResponseDTO.java
  src/main/java/dgu/newsee/domain/news/entity/News.java
  src/main/java/dgu/newsee/domain/news/entity/SavedNews.java
  src/main/java/dgu/newsee/domain/news/entity/SavedNewsId.java
  src/main/java/dgu/newsee/domain/news/repository/NewsRepository.java
  src/main/java/dgu/newsee/domain/news/repository/SavedNewsRepository.java
  src/main/java/dgu/newsee/domain/news/service/NewsService.java
  src/main/java/dgu/newsee/domain/news/util/NewsCrawlResult.java
  src/main/java/dgu/newsee/domain/news/util/NewsCrawler.java
  src/main/java/dgu/newsee/global/config/SecurityConfig.java
Labels: ✨ feature, 🐰 예인 작업

#28 [Feature] #7 - 단어장 관련 API 구현
  src/main/java/dgu/newsee/domain/words/controller/SavedWordController.java
  src/main/java/dgu/newsee/domain/words/converter/SavedWordConverter.java
  src/main/java/dgu/newsee/domain/words/dto/SavedWordDTO.java
  src/main/java/dgu/newsee/domain/words/entity/SavedWord.java
  src/main/java/dgu/newsee/domain/words/entity/Word.java
  src/main/java/dgu/newsee/domain/words/repository/SavedWordRepository.java
  src/main/java/dgu/newsee/domain/words/repository/WordRepository.java
  src/main/java/dgu/newsee/domain/words/service/SavedWordService.java
  src/main/java/dgu/newsee/domain/words/service/SavedWordServiceImpl.java
  src/main/java/dgu/newsee/global/exception/SavedWordException.java
  src/main/java/dgu/newsee/global/payload/ResponseCode.java
Labels: ✨ feature, 🐈‍⬛ 영신 작업

#33 [Refactor] #31 - word, savedWord entity에 BaseEntity 추가
  src/main/java/dgu/newsee/domain/words/entity/SavedWord.java
  src/main/java/dgu/newsee/domain/words/entity/Word.java
Labels: :recycle: refactor, 🐈‍⬛ 영신 작업

#35 [Refactor] #34 - 프로필 조회에 저장된 단어 수 추가
  src/main/java/dgu/newsee/domain/user/converter/UserConverter.java
  src/main/java/dgu/newsee/domain/user/dto/UserDTO.java
  src/main/java/dgu/newsee/domain/user/service/UserServiceImpl.java
Labels: :recycle: refactor, 🐈‍⬛ 영신 작업

#40 [Feature] #32 - 프론트 배포 주소 cors 설정
  src/main/java/dgu/newsee/global/config/WebConfig.java
Labels: ✨ feature, 🐸 하은 작업

#45 [Fix] #44 - 뉴스 id Word 저장 오류 해결
  src/main/java/dgu/newsee/domain/transformednews/service/TransformedNewsService.java
  src/main/java/dgu/newsee/domain/words/entity/Word.java
Labels: :bug: fix, 🐰 예인 작업

#47 [Refactor] #46 - 프론트 테스트 배포 주소 추가
  src/main/java/dgu/newsee/global/config/WebConfig.java
Labels: :recycle: refactor, 🐸 하은 작업

#48 [Feature] #9 - 뉴스 관련 API 구현
  src/main/java/dgu/newsee/domain/news/controller/UserNewsController.java
  src/main/java/dgu/newsee/domain/news/converter/NewsConverter.java
  src/main/java/dgu/newsee/domain/news/dto/NewsDTO.java
  src/main/java/dgu/newsee/domain/news/dto/NewsDetailDTO.java
  src/main/java/dgu/newsee/domain/news/dto/SaveNewsResponseDTO.java
  src/main/java/dgu/newsee/domain/news/dto/SavedNewsDTO.java
  src/main/java/dgu/newsee/domain/news/entity/SavedNews.java
  src/main/java/dgu/newsee/domain/news/repository/NewsQueryRepository.java
  src/main/java/dgu/newsee/domain/news/repository/SavedNewsRepository.java
  src/main/java/dgu/newsee/domain/news/service/NewsService.java
  src/main/java/dgu/newsee/domain/news/service/NewsServiceImpl.java
  src/main/java/dgu/newsee/domain/transformednews/repository/NewsTransformedRepository.java
  src/main/java/dgu/newsee/domain/words/repository/WordRepository.java
  src/main/java/dgu/newsee/global/config/SecurityConfig.java
  src/main/java/dgu/newsee/global/exception/NewsException.java
Labels: ✨ feature, 🐈‍⬛ 영신 작업

#51 [Refactor] #50 - 뉴스 북마크 시 response값 수정
  src/main/java/dgu/newsee/domain/news/dto/SaveNewsResponseDTO.java
  src/main/java/dgu/newsee/domain/news/service/NewsServiceImpl.java
Labels: :recycle: refactor, 🐈‍⬛ 영신 작업

#54 [Refactor] #52 - 서비스 계층 책임 분리 및 DTO 생성 일관성 향상
  src/main/java/dgu/newsee/domain/news/converter/NewsConverter.java
  src/main/java/dgu/newsee/domain/news/dto/SaveNewsResponseDTO.java
  src/main/java/dgu/newsee/domain/news/service/NewsServiceImpl.java
Labels: :recycle: refactor, 🐸 하은 작업

#55 [Fix] #44 - 오류 반환 코드 통일
  src/main/java/dgu/newsee/domain/crawlednews/service/NewsService.java
  src/main/java/dgu/newsee/domain/crawlednews/util/NewsParserUtil.java
  src/main/java/dgu/newsee/global/payload/ResponseCode.java
Labels: :bug: fix, 🐰 예인 작업

#57 [Refactor] #56 - AI 변환 서버 URL을 코드 하드코딩 대신 application.yml의 환경변수로 분리
  .github/workflows/main.yml
  src/main/java/dgu/newsee/domain/transformednews/service/TransformedNewsService.java
  src/main/resources/application.yml
Labels: :recycle: refactor, 🐸 하은 작업
